/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <stdio.h>
#include <stdlib.h>

//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
long long sub_400930();
// long long  __isoc99_fscanf(long long, long long, long long); weak
// int puts(const char *s);
// int fclose(FILE *stream);
// size_t strlen(const char *s);
// int system(const char *command);
// int printf(const char *format, ...);
// int fgetc(FILE *stream);
// void srand(unsigned int seed);
// char *fgets(char *s, int n, FILE *stream);
// int strcmp(const char *s1, const char *s2);
// int getchar(void);
// long long strtol(const char *nptr, char **endptr, int base);
// void *memcpy(void *dest, const void *src, size_t n);
// time_t time(time_t *timer);
// void *malloc(size_t size);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// FILE *fopen(const char *filename, const char *modes);
// int atoi(const char *nptr);
// void  exit(int status);
// int rand(void);
// long long _gmon_start__(void); weak
signed long long deregister_tm_clones();
long long register_tm_clones();
signed long long _do_global_dtors_aux();
long long frame_dummy();
long long read_number();
int  read_string(long long a1, int a2);
int  show(int a1);
int prepare();
int title();
int print_hall_of_fame();
int menu();
void prize();
unsigned long long update();
unsigned long long change_name();
unsigned long long play();
long long game();
unsigned long long load();
int startup();
int  main(int argc, const char **argv, const char **envp);
void  _libc_csu_init(unsigned int a1, long long a2, long long a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

long long ( *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
long long ( *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
long long (*qword_603010)(void) = NULL; // weak
FILE *stdout; // idb
FILE *stdin; // idb
char completed_7594; // weak
int words_size; // weak
int score; // weak
char *hall_of_fame; // idb
void *dest; // idb
char name[32]; // idb
void *words[32]; // idb
int best_scores[]; // weak
int dword_603290; // weak

long long read_number()
{
  char s; // [rsp+10h] [rbp-20h]
  unsigned long long v2; // [rsp+28h] [rbp-8h]

  fgets(&s, 16, stdin);
  return (unsigned int)atoi(&s);
}

//----- (0000000000400BFD) ----------------------------------------------------
int  read_string(long long a1, int a2)
{
  char *v2; // rax
  char v4; // [rsp+1Bh] [rbp-5h]
  int i; // [rsp+1Ch] [rbp-4h]

  for ( i = 0; i <= a2; ++i )
  {
    v4 = getchar();
    if ( v4 == 10 )
      break;
    *(char *)(a1 + i) = v4;
  }
  v2 = (char *)(i + a1);
  *v2 = 0;
  while ( v4 != 10 )
  {
    v2 = getchar();
    v4 = (char)v2;
  }
  return (signed int)v2;
}

//----- (0000000000400C68) ----------------------------------------------------
int  show(int a1)
{
  int result; // eax

  result = a1;
  switch ( a1 )
  {
    case 0:
      printf("\n    ||===== ");
      printf("\n    ||    | ");
      printf("\n    ||   \\O/");
      printf("\n    ||    | ");
      printf("\n    ||   / \\");
      result = printf("\n    || ");
      break;
    case 1:
      printf("\n    ||===== ");
      printf("\n    ||    | ");
      printf("\n    ||   \\O/");
      printf("\n    ||    | ");
      printf("\n    ||     \\");
      result = printf("\n    || ");
      break;
    case 2:
      printf("\n    ||===== ");
      printf("\n    ||    | ");
      printf("\n    ||   \\O/");
      printf("\n    ||    | ");
      printf("\n    ||      ");
      result = printf("\n    || ");
      break;
    case 3:
      printf("\n    ||===== ");
      printf("\n    ||    | ");
      printf("\n    ||   \\O/");
      printf("\n    ||      ");
      printf("\n    ||      ");
      result = printf("\n    || ");
      break;
    case 4:
      printf("\n    ||===== ");
      printf("\n    ||    | ");
      printf("\n    ||   \\O ");
      printf("\n    ||      ");
      printf("\n    ||      ");
      result = printf("\n    || ");
      break;
    case 5:
      printf("\n    ||===== ");
      printf("\n    ||    | ");
      printf("\n    ||    O ");
      printf("\n    ||      ");
      printf("\n    ||      ");
      result = printf("\n    || ");
      break;
    default:
      return result;
  }
  return result;
}

//----- (0000000000400EC1) ----------------------------------------------------
int prepare()
{
  unsigned int v0; // eax
  signed int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 4; ++i )
    (&hall_of_fame)[i] = (char *)malloc(0x100uLL);
  v0 = time(0LL);
  srand(v0);
  return setvbuf(stdout, 0LL, 2, 0LL);
}

//----- (0000000000400F28) ----------------------------------------------------
int title()
{
  puts("  _                                             ");
  puts(" | |                                            ");
  puts(" | |__   __ _ _ __   __ _ _ __ ___   __ _ _ __  ");
  puts(" | '_ \\ / _` | '_ \\ / _` | '_ ` _ \\ / _` | '_ \\ ");
  puts(" | | | | (_| | | | | (_| | | | | | | (_| | | | | ");
  puts(" |_| |_|\\__,_|_| |_|\\__, |_| |_| |_|\\__,_|_| |_| ");
  puts("                     __/ |                      ");
  puts("                    |___/  ");
  return puts("                                               ");
}

//----- (0000000000400F89) ----------------------------------------------------
int print_hall_of_fame()
{
  int result; // eax
  signed int i; // [rsp+Ch] [rbp-4h]

  puts("\n[+] \\ /   Hangman    \\ /");
  result = puts("     0  Hall of Fame  0\n");
  for ( i = 0; i <= 4; ++i )
  {
    printf("    %d. Name  : %s\n", (unsigned int)(i + 1), (&hall_of_fame)[i]);
    result = printf("       Score : %u\n\n", (unsigned int)best_scores[i]);
  }
  return result;
}
// 603280: using guessed type int best_scores[];

//----- (0000000000400FFF) ----------------------------------------------------
int menu()
{
  printf("\n[+] Greetings %s! What would you like to do?\n", name);
  puts("    1. Play");
  puts("    2. Score");
  puts("    3. Hall of Fame");
  puts("    4. Prize");
  puts("    5. Rename");
  puts("    6. Restart");
  puts("    7. Exit");
  return printf("\n[+] Your choice: ");
}

//----- (000000000040106F) ----------------------------------------------------
void prize()
{
  signed int i; // [rsp+Ch] [rbp-4h]

  for ( i = 0; i <= 4; ++i )
  {
    if ( !strcmp(name, (&hall_of_fame)[i]) )
    {
      printf("\n[+] Flag: ");
      system("cat flag");
      exit(0);
    }
  }
  if ( i == 5 )
  {
    puts("\n[+] You are not eligible for the prize yet.");
    printf("    Get %u more point(s) to redeem flag!\n", (unsigned int)(dword_603290 - score));
  }
}
// 603100: using guessed type int score;
// 603290: using guessed type int dword_603290;

//----- (00000000004010FF) ----------------------------------------------------
unsigned long long update()
{
  unsigned long long result; // rax
  size_t v1; // rax
  int v2; // ST04_4
  char *v3; // ST08_8
  signed int i; // [rsp+0h] [rbp-10h]

  result = (unsigned int)score;
  if ( dword_603290 < (unsigned int)score )
  {
    dword_603290 = score;
    v1 = strlen(name);
    result = (unsigned long long)memcpy(dest, name, v1 + 1);
    for ( i = 4; i > 0; --i )
    {
      result = (unsigned int)best_scores[i - 1];
      if ( best_scores[i] > (unsigned int)result )
      {
        v2 = best_scores[i - 1];
        best_scores[i - 1] = best_scores[i];
        best_scores[i] = v2;
        v3 = (&hall_of_fame)[i - 1];
        (&hall_of_fame)[i - 1] = (&hall_of_fame)[i];
        result = i;
        (&hall_of_fame)[i] = v3;
      }
    }
  }
  return result;
}
// 603100: using guessed type int score;
// 603280: using guessed type int best_scores[];
// 603290: using guessed type int dword_603290;

//----- (0000000000401209) ----------------------------------------------------
unsigned long long change_name()
{
  int v0; // eax
  size_t v1; // rax
  signed int i; // [rsp+Ch] [rbp-414h]
  char s1; // [rsp+10h] [rbp-410h]
  unsigned long long v5; // [rsp+418h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  printf("\n[+] Enter your new name: ");
  v0 = strlen(name);
  read_string((long long)&s1, v0);
  for ( i = 0; i <= 4; ++i )
  {
    if ( !strcmp(&s1, (&hall_of_fame)[i]) )
    {
      puts("\n[+] Sorry, name is already taken.");
      return __readfsqword(0x28u) ^ v5;
    }
  }
  v1 = strlen(&s1);
  memcpy(name, &s1, v1 + 1);
  return __readfsqword(0x28u) ^ v5;
}

//----- (00000000004012DA) ----------------------------------------------------
unsigned long long play()
{
  long long *v0; // rax
  char v2; // [rsp+Fh] [rbp-B1h]
  int v3; // [rsp+10h] [rbp-B0h]
  int i; // [rsp+14h] [rbp-ACh]
  int j; // [rsp+14h] [rbp-ACh]
  int k; // [rsp+14h] [rbp-ACh]
  int l; // [rsp+14h] [rbp-ACh]
  unsigned int v8; // [rsp+18h] [rbp-A8h]
  signed int v9; // [rsp+1Ch] [rbp-A4h]
  char s[8]; // [rsp+20h] [rbp-A0h]
  long long v11; // [rsp+28h] [rbp-98h]
  long long v12; // [rsp+30h] [rbp-90h]
  long long v13; // [rsp+38h] [rbp-88h]
  long long v14; // [rsp+40h] [rbp-80h]
  long long v15; // [rsp+48h] [rbp-78h]
  long long v16; // [rsp+50h] [rbp-70h]
  long long v17; // [rsp+58h] [rbp-68h]
  char v18[72]; // [rsp+60h] [rbp-60h]
  unsigned long long v19; // [rsp+A8h] [rbp-18h]

  v19 = __readfsqword(0x28u);
  v3 = 5;
  v0 = words[rand() % words_size];
  *(long long *)s = *v0;
  v11 = v0[1];
  v12 = v0[2];
  v13 = v0[3];
  v14 = v0[4];
  v15 = v0[5];
  v16 = v0[6];
  v17 = v0[7];
  for ( i = 0; i < strlen(s); ++i )
    v18[i] = 95;
  v18[i] = 0;
  puts("\n[+] Game begin!");
  v8 = strlen(v18);
  while ( v3 > 0 && (signed int)v8 > 0 )
  {
    v9 = 0;
    show(v3);
    for ( j = 0; j < strlen(v18); ++j )
      printf("%c ", (unsigned int)v18[j]);
    printf("\n\n    Guess a letter: ");
    v2 = getchar();
    for ( k = 0; k < strlen(s); ++k )
    {
      if ( s[k] == v2 && v18[k] != v2 )
      {
        v18[k] = v2;
        --v8;
        v9 = 1;
      }
    }
    if ( v9 )
    {
      printf("    Great job! %d letter(s) to go.\n", v8);
    }
    else
    {
      printf("    Better luck next time. %d letter(s) to go.\n", v8);
      --v3;
    }
    while ( v2 != 10 )
      v2 = getchar();
  }
  show(v3);
  for ( l = 0; l < strlen(s); ++l )
    printf("%c ", (unsigned int)s[l]);
  if ( v3 )
  {
    score += 100;
    printf("\n\n[+] Congratulations! Your score: %u", (unsigned int)score);
  }
  else
  {
    printf("\n\n[+] You are dead. Try again. Your score: %u", (unsigned int)score);
  }
  getchar();
  return __readfsqword(0x28u) ^ v19;
}
// 6030FC: using guessed type int words_size;
// 603100: using guessed type int score;
// 4012DA: using guessed type char var_60[72];

//----- (0000000000401608) ----------------------------------------------------
long long game()
{
  long long result; // rax

  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              update();
              menu();
              result = read_number();
              if ( (int)result != 1 )
                break;
              play();
            }
            if ( (int)result != 2 )
              break;
            printf("\n[+] Your score: %u\n", (unsigned int)score);
          }
          if ( (int)result != 3 )
            break;
          print_hall_of_fame();
        }
        if ( (int)result != 4 )
          break;
        prize();
      }
      if ( (int)result != 5 )
        break;
      change_name();
    }
    if ( (int)result == 6 )
      break;
    if ( (int)result == 7 )
    {
      puts("\n[+] Thanks for playing!");
      exit(0);
    }
  }
  return result;
}
// 603100: using guessed type int score;

//----- (00000000004016C2) ----------------------------------------------------
unsigned long long load()
{
  size_t v0; // rax
  size_t v1; // rax
  char v3; // [rsp+Fh] [rbp-A1h]
  int v4; // [rsp+10h] [rbp-A0h]
  signed int i; // [rsp+10h] [rbp-A0h]
  signed int v6; // [rsp+14h] [rbp-9Ch]
  FILE *stream; // [rsp+18h] [rbp-98h]
  FILE *streama; // [rsp+18h] [rbp-98h]
  char src[136]; // [rsp+20h] [rbp-90h]
  unsigned long long v10; // [rsp+A8h] [rbp-8h]

  v10 = __readfsqword(0x28u);
  stream = fopen("hall_of_fame", "r");
  if ( !stream )
    exit(1);
  v4 = 0;
  v6 = 0;
  while ( 1 )
  {
    v3 = fgetc(stream);
    if ( v3 == -1 )
      break;
    if ( v3 == 58 )
    {
      memcpy((&hall_of_fame)[v6], src, v4);
      v4 = 0;
    }
    else if ( v3 == 10 )
    {
      src[v4] = 0;
      best_scores[v6++] = strtol(src, 0LL, 10);
      v4 = 0;
      if ( v6 > 5 )
        break;
    }
    else
    {
      src[v4++] = v3;
    }
  }
  fclose(stream);
  streama = fopen("wordlist", "r");
  if ( !streama )
    exit(1);
  for ( i = 0; i <= 63 && (unsigned int)__isoc99_fscanf(streama, "%s", src) != -1; ++i )
  {
    v0 = strlen(src);
    words[i] = malloc(v0 + 1);
    v1 = strlen(src);
    memcpy(words[i], src, v1 + 1);
  }
  words_size = i;
  fclose(streama);
  return __readfsqword(0x28u) ^ v10;
}
// 400940: using guessed type long long  __isoc99_fscanf(long long, long long, long long);
// 6030FC: using guessed type int words_size;
// 603280: using guessed type int best_scores[];
// 4016C2: using guessed type char src[136];

//----- (0000000000401925) ----------------------------------------------------
int startup()
{
  int result; // eax
  signed int v1; // [rsp+8h] [rbp-8h]
  signed int i; // [rsp+Ch] [rbp-4h]

  load();
  do
  {
    v1 = 1;
    printf("[+] Enter your name: ");
    result = read_string((long long)name, 20);
    for ( i = 0; i <= 4; ++i )
    {
      result = strcmp(name, (&hall_of_fame)[i]);
      if ( !result )
      {
        result = puts("[+] Sorry, name is already taken.\n");
        v1 = 0;
        break;
      }
    }
  }
  while ( !v1 );
  return result;
}

//----- (00000000004019A9) ----------------------------------------------------
int   main(int argc, const char **argv, const char **envp)
{
  prepare();
  while ( 1 )
  {
    title();
    startup();
    game();
  }
}